window.addEventListener('click', event => { const link = event.target.closest('a[href^="#place-place-"]'); if (link) { event.preventDefault(); location.hash = link.getAttribute('href').replace('#place-place-', '#place-'); } });
window.addEventListener('hashchange', () => { if (location.hash.startsWith('#place-place-')) location.hash = location.hash.replace('#place-place-', '#place-'); });
window.addEventListener('load', () => { places.push(...places.map(place => ({ ...place, id: `place-${place.id}`, cityId: '__detail' }))); });
const cities = [
  ['indore', 'Indore', 'Madhya Pradesh', "India's cleanest city, known for generous food, lively bazaars and palace stories.", 'https://images.unsplash.com/photo-1595658658481-d53d3f999875?auto=format&fit=crop&w=900&q=80'],
  ['bhopal', 'Bhopal', 'Madhya Pradesh', 'Lakes, museums and old-city flavours in a quietly creative city.', 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=900&q=80'],
  ['ujjain', 'Ujjain', 'Madhya Pradesh', 'A riverside spiritual city where ancient rituals meet hospitality.', 'https://images.unsplash.com/photo-1600100397608-f0109a9f3d16?auto=format&fit=crop&w=900&q=80'],
  ['jaipur', 'Jaipur', 'Rajasthan', 'Rose-coloured forts, craft markets and royal architecture.', 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=900&q=80'],
  ['delhi', 'Delhi', 'Delhi', 'A layered capital with monuments, street food and neighbourhood culture.', 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=900&q=80'],
  ['mumbai', 'Mumbai', 'Maharashtra', 'Sea-facing promenades, legendary food and unstoppable energy.', 'https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?auto=format&fit=crop&w=900&q=80'],
  ['agra', 'Agra', 'Uttar Pradesh', 'A city of marble, gardens and a world-famous monument.', 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=900&q=80'],
  ['varanasi', 'Varanasi', 'Uttar Pradesh', 'Sacred ghats, morning boats and an unforgettable Ganga rhythm.', 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?auto=format&fit=crop&w=900&q=80']
].map(([id, name, state, description, image]) => ({ id, name, state, description, image }));

const places = [
  ['indore', 'Rajwada Palace', 'Historical Places', "An 18th-century palace at the heart of Indore's old city and markets.", 'Rajwada Square, Indore', 4.7, 410, 'https://images.unsplash.com/photo-1624624684032-6f3f03c5c2a9?auto=format&fit=crop&w=800&q=80'],
  ['indore', 'Lal Bagh Palace', 'Historical Places', 'A grand heritage palace with European-inspired interiors and gardens.', 'Revenue Colony, Indore', 4.6, 320, 'https://images.unsplash.com/photo-1606298855672-3efb63017be8?auto=format&fit=crop&w=800&q=80'],
  ['indore', 'Sarafa Bazaar', 'Food & Restaurants', 'A beloved night food market for poha-jalebi and local treats.', 'Maharaja Tukoji Rao Holker Cloth Market, Indore', 4.8, 780, 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80'],
  ['indore', 'Chappan Dukan', 'Food & Restaurants', 'A buzzing strip of snacks, sweets, coffee and local favourites.', 'New Palasia, Indore', 4.6, 690, 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=800&q=80'],
  ['indore', 'Patalpani Waterfall', 'Parks & Nature', 'A scenic monsoon escape surrounded by green hills.', 'Mhow Tehsil, Indore district', 4.5, 540, 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=80'],
  ['indore', 'Regional Park', 'Parks & Nature', 'Open lawns, boating and sunset walks around an urban lake.', 'Pipliyapala, Indore', 4.4, 450, 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=80'],
  ['indore', 'Central Museum', 'Tourist Attractions', 'A compact collection of sculptures, coins and archaeology.', 'Navlakha, Indore', 4.3, 210, 'https://images.unsplash.com/photo-1564399579883-451a5d44ec08?auto=format&fit=crop&w=800&q=80'],
  ['indore', 'Annapurna Temple', 'Religious Places', 'A colourful temple with a detailed entrance and peaceful courtyard.', 'Kranti Kriplani Nagar, Indore', 4.6, 380, 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80'],
  ['indore', 'The Monroe Cafe', 'Cafes', 'A relaxed coffee stop for slow mornings and desserts.', 'Vijay Nagar, Indore', 4.5, 280, 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80'],
  ['bhopal', 'Upper Lake', 'Parks & Nature', 'A peaceful lakefront for boat rides and golden-hour views.', 'Bhojtaal, Bhopal', 4.6, 510, 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=80'],
  ['bhopal', 'Tribal Museum', 'Tourist Attractions', 'A vibrant museum celebrating central Indian traditions.', 'Shyamla Hills, Bhopal', 4.8, 430, 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&w=800&q=80'],
  ['ujjain', 'Mahakaleshwar Temple', 'Religious Places', 'One of India’s most revered Shiva temples on the Shipra.', 'Mahakal Marg, Ujjain', 4.8, 920, 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80'],
  ['jaipur', 'Amber Fort', 'Historical Places', 'A hilltop fort of courtyards, mirror work and views.', 'Devisinghpura, Amer', 4.7, 890, 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80'],
  ['delhi', "Humayun's Tomb", 'Historical Places', 'A serene garden tomb and Mughal architecture landmark.', 'Mathura Road, New Delhi', 4.7, 760, 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80'],
  ['agra', 'Taj Mahal', 'Tourist Attractions', 'An enduring monument to love, best experienced in early light.', 'Dharmapuri, Agra', 4.9, 1200, 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80'],
  ['varanasi', 'Dashashwamedh Ghat', 'Religious Places', 'A lively riverside ghat known for evening ceremonies.', 'Godowlia, Varanasi', 4.8, 860, 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?auto=format&fit=crop&w=800&q=80']
].map((p, id) => ({ id: `place-${id}`, cityId: p[0], name: p[1], category: p[2], description: p[3], address: p[4], rating: p[5], popularity: p[6], image: p[7], hours: 'Demo hours: check venue before visiting', fee: 'Demo information', contact: 'Demo information only' }));

const categories = ['All', 'Tourist Attractions', 'Food & Restaurants', 'Historical Places', 'Entertainment', 'Shopping', 'Parks & Nature', 'Cafes', 'Religious Places'];
let user = null, authMode = 'login', currentCity = 'indore', filter = 'All', search = '', sortMode = 'popular';
const $ = selector => document.querySelector(selector);
const esc = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));

function storageKey() { return user ? `cm-fav-${user.id}` : 'cm-fav-guest'; }
function favorites() { return JSON.parse(localStorage.getItem(storageKey()) || '[]'); }
function mapsUrl(place, directions = false) { const type = directions ? 'dir/?api=1&destination=' : 'search/?api=1&query='; return `https://www.google.com/maps/${type}${encodeURIComponent(`${place.name}, ${place.address}`)}`; }
function notify(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); }
function placeCard(place) { return `<article class="place-card"><img src="${place.image}" alt="${esc(place.name)}" loading="lazy"><div><div class="place-meta"><span>${esc(place.category)}</span><span class="rating">★ ${place.rating}</span></div><h3>${esc(place.name)}</h3><p>${esc(place.description)}</p><p>⌖ ${esc(place.address)}</p><div class="card-actions"><a class="btn btn-coral btn-small" href="#place-${place.id}">View details</a><a class="btn btn-ghost btn-small" target="_blank" rel="noopener" href="${mapsUrl(place, true)}">Navigate ↗</a></div></div></article>`; }
function cityCard(city) { return `<article class="city-card"><img src="${city.image}" alt="${esc(city.name)} city view" loading="lazy"><div><h3>${esc(city.name)}</h3><p>${esc(city.description)}</p><a class="btn btn-ghost" href="#city-${city.id}">Explore city →</a></div></article>`; }
function home() { return `<section class="hero"><div><span class="kicker">A more local way to travel</span><h1>Explore India like a local.</h1><p>Find the places that make a city feel alive, from iconic landmarks to the cafe around the corner.</p><div class="hero-actions"><a class="btn btn-coral" href="#cities">Explore cities <span>→</span></a><a class="btn btn-ghost" href="#about">See how it works</a></div></div><div class="hero-art"><span><strong>8 cities</strong>curated for your next story</span></div></section><section class="section wrap" id="cities"><div class="section-head"><div><span class="kicker">Start somewhere beautiful</span><h2 class="section-title">Which city is calling?</h2></div><p class="muted">Handpicked starting points for curious travellers.</p></div><div class="city-grid">${cities.map(cityCard).join('')}</div></section><section class="section wrap"><span class="kicker">Browse by mood</span><h2 class="section-title">Make room for a little wonder.</h2><div class="category-row">${categories.slice(1).map(category => `<a class="category" href="#city-indore?category=${encodeURIComponent(category)}">${category}</a>`).join('')}</div></section><section class="section how" id="about"><div class="wrap"><span class="kicker">Simple by design</span><h2 class="section-title">Three steps to a better day out.</h2><div class="steps"><div class="step"><b>01</b><h3>Choose your city</h3><p>Start with the city you are in, or the one you cannot wait to visit.</p></div><div class="step"><b>02</b><h3>Follow your curiosity</h3><p>Search, filter and browse by food, history, nature, culture or a local feeling.</p></div><div class="step"><b>03</b><h3>Go make a memory</h3><p>Save your finds and open reliable Google Maps directions when it is time to head out.</p></div></div></div></section>`; }
function cityPage(id) { const city = cities.find(item => item.id === id) || cities[0]; currentCity = city.id; let list = places.filter(place => place.cityId === city.id); if (search) list = list.filter(place => `${place.name} ${place.category} ${place.description}`.toLowerCase().includes(search.toLowerCase())); if (filter !== 'All') list = list.filter(place => place.category === filter); if (sortMode === 'rating') list.sort((a, b) => b.rating - a.rating); if (sortMode === 'name') list.sort((a, b) => a.name.localeCompare(b.name)); return `<section class="city-banner"><div class="wrap"><span class="kicker">${city.state}</span><h1>Explore ${city.name}</h1><p>${city.description}</p></div></section><section class="wrap dashboard"><div class="toolbar"><input id="placeSearch" value="${esc(search)}" placeholder="Search places, food, experiences..." aria-label="Search places"><select id="sortPlaces"><option value="popular" ${sortMode === 'popular' ? 'selected' : ''}>Most popular</option><option value="rating" ${sortMode === 'rating' ? 'selected' : ''}>Highest rated</option><option value="name" ${sortMode === 'name' ? 'selected' : ''}>Name A-Z</option></select></div><div class="chips">${categories.map(item => `<button class="${filter === item ? 'active' : ''}" data-filter="${item}">${item}</button>`).join('')}</div><p class="muted">${list.length} places in ${city.name}</p><div class="place-grid">${list.length ? list.map(placeCard).join('') : '<div class="empty" style="grid-column:1/-1"><h3>No places found</h3><p>Try another search or category.</p></div>'}</div></section>`; }
function detailPage(id) { const place = places.find(item => item.id === id); if (!place) return '<section class="section wrap"><h2>Place not found</h2><a class="btn btn-coral" href="#cities">Back to cities</a></section>'; const saved = favorites().includes(place.id); return `<section class="wrap detail"><img src="${place.image}" alt="${esc(place.name)}"><div><span class="kicker">${esc(place.category)} · ${esc(cities.find(city => city.id === place.cityId)?.name || 'India')}</span><h1>${esc(place.name)}</h1><p class="muted">${esc(place.description)}</p><div class="facts"><div><small>Rating</small><b>★ ${place.rating} · ${place.popularity} visits</b></div><div><small>Opening hours</small><b>${esc(place.hours)}</b></div><div><small>Entry fee</small><b>${esc(place.fee)}</b></div><div><small>Contact</small><b>${esc(place.contact)}</b></div></div><p>⌖ ${esc(place.address)}</p><div class="hero-actions"><a class="btn btn-coral" target="_blank" rel="noopener" href="${mapsUrl(place, true)}">Get directions ↗</a><a class="btn btn-ghost" target="_blank" rel="noopener" href="${mapsUrl(place)}">Open in Google Maps</a><button class="btn btn-ghost" id="favoriteButton" data-place="${place.id}">${saved ? '♥ Saved' : '♡ Add to favorites'}</button></div><div class="notice">Hours, fees and contact details are demo information where official details may change. Check the venue before travelling.</div></div></section>`; }
function favoritesPage() { if (!user) return '<section class="section wrap"><span class="kicker">Personal collection</span><h1 class="section-title">Log in to save places.</h1><button class="btn btn-coral" id="openAuth">Log in</button></section>'; const saved = places.filter(place => favorites().includes(place.id)); return `<section class="intro"><div class="wrap"><span class="kicker">${esc(user.name)}'s collection</span><h1>Places worth remembering.</h1><p class="muted">Your saved discoveries, ready for the next day out.</p></div></section><section class="wrap dashboard">${saved.length ? `<div class="place-grid">${saved.map(placeCard).join('')}</div>` : '<div class="empty"><h3>Your collection is empty.</h3><p>Tap the heart on a place you would like to remember.</p><a class="btn btn-coral" href="#cities">Find a place</a></div>'}</section>`; }
function render() { const route = location.hash.slice(1) || 'home'; const [path, query] = route.split('?'); if (path === 'home') $('#app').innerHTML = home(); else if (path === 'cities') $('#app').innerHTML = `<section class="intro"><div class="wrap"><span class="kicker">The CityMate atlas</span><h1>Pick a city. Follow the feeling.</h1><p class="muted">Eight Indian cities to begin with, and more to come.</p></div></section><section class="section wrap"><div class="city-grid">${cities.map(cityCard).join('')}</div></section>`; else if (path.startsWith('city-')) { if (query) new URLSearchParams(query).forEach((value, key) => { if (key === 'category') filter = value; }); $('#app').innerHTML = cityPage(path.slice(5)); } else if (path.startsWith('place-')) $('#app').innerHTML = detailPage(path.slice(6)); else if (path === 'favorites') $('#app').innerHTML = favoritesPage(); else $('#app').innerHTML = home(); updateAuth(); window.scrollTo(0, 0); }
function updateAuth() { $('#authButton').textContent = user ? 'Sign out' : 'Log in'; }
function openAuth(mode = 'login') { authMode = mode; $('#authModal').hidden = false; $('#authTitle').textContent = mode === 'login' ? 'Log in' : 'Create your account'; $('#authSubtitle').textContent = mode === 'login' ? 'Your next memorable stop is waiting.' : 'Save discoveries and build your own city guide.'; $('#nameField').hidden = mode === 'login'; $('#confirmField').hidden = mode === 'login'; $('#authSubmit').innerHTML = mode === 'login' ? 'Log in <span>→</span>' : 'Create account <span>→</span>'; $('#switchAuth').textContent = mode === 'login' ? 'New here? Create an account' : 'Already have an account? Log in'; $('#authError').textContent = ''; $('#authEmail').focus(); }

$('#authButton').onclick = () => { if (user) { user = null; localStorage.removeItem('cm-session'); render(); notify('You are signed out.'); } else openAuth(); };
$('#closeModal').onclick = () => { $('#authModal').hidden = true; };
$('#switchAuth').onclick = () => openAuth(authMode === 'login' ? 'register' : 'login');
$('#menuButton').onclick = () => $('#nav').classList.toggle('open');
$('#searchToggle').onclick = () => { location.hash = `city-${currentCity}`; setTimeout(() => $('#placeSearch')?.focus(), 50); };
$('#authForm').onsubmit = async event => { event.preventDefault(); const email = $('#authEmail').value.trim().toLowerCase(); const password = $('#authPassword').value; const users = JSON.parse(localStorage.getItem('cm-users') || '[]'); if (authMode === 'register') { if (!$('#authName').value.trim()) return $('#authError').textContent = 'Please enter your full name.'; if (password !== $('#authConfirm').value) return $('#authError').textContent = 'Passwords do not match.'; if (users.some(item => item.email === email)) return $('#authError').textContent = 'An account with this email already exists.'; const account = { id: `user-${Date.now()}`, name: $('#authName').value.trim(), email, passwordHash: await hashPassword(password) }; users.push(account); localStorage.setItem('cm-users', JSON.stringify(users)); user = account; notify('Account created. Welcome to CityMate.'); } else { const passwordHash = await hashPassword(password); user = users.find(item => item.email === email && item.passwordHash === passwordHash); if (!user) return $('#authError').textContent = 'Email or password is incorrect.'; notify(`Welcome back, ${user.name}.`); } localStorage.setItem('cm-session', JSON.stringify({ id: user.id })); $('#authModal').hidden = true; render(); };
async function hashPassword(value) { const buffer = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)); return [...new Uint8Array(buffer)].map(byte => byte.toString(16).padStart(2, '0')).join(''); }
document.addEventListener('click', event => { const chip = event.target.closest('[data-filter]'); if (chip) { filter = chip.dataset.filter; render(); } if (event.target.id === 'openAuth') openAuth(); if (event.target.id === 'favoriteButton') { if (!user) return openAuth(); const id = event.target.dataset.place; const current = favorites(); localStorage.setItem(storageKey(), JSON.stringify(current.includes(id) ? current.filter(item => item !== id) : [...current, id])); notify(current.includes(id) ? 'Removed from favorites.' : 'Saved to favorites.'); render(); } });
document.addEventListener('input', event => { if (event.target.id === 'placeSearch') { search = event.target.value; render(); setTimeout(() => { const input = $('#placeSearch'); input?.focus(); input?.setSelectionRange(search.length, search.length); }, 0); } });
document.addEventListener('change', event => { if (event.target.id === 'sortPlaces') { sortMode = event.target.value; render(); } });
window.onhashchange = () => { search = ''; filter = 'All'; sortMode = 'popular'; render(); };
const session = JSON.parse(localStorage.getItem('cm-session') || 'null'); if (session) user = JSON.parse(localStorage.getItem('cm-users') || '[]').find(item => item.id === session.id) || null; render();
